name: Nexus Mods

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
        
    - name: Download the release asset
      run: wget "https://github.com/0xDezzy/Unlimited-Outposts-CCR/archive/refs/tags/v${GITHUB_REF:11}.zip" -O "release.zip"

    - name: Upload
      uses: hmlendea/nexusmods-update@latest
      with:
        account_email_address: ${{secrets.NEXUS_UPLOADER_USERNAME}}
        account_password: ${{secrets.NEXUS_UPLOADER_PASSWORD}}
        nexus_game_id: "starfield"
        nexus_mod_id: "2924"
        mod_file_name: "Unlimited Outposts - CCR"
        mod_version: ${{github.ref_name}}
        file_description: "Changelog: https://github.com/0xDezzy/Unlimited-Outposts-CCR/releases/tag/${{github.ref_name}}"
        file_path: "release.zip"