name: Nexus Mods

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release:
          draft: false
          prerelease: false
    
    - name: Download the release asset
      run: wget "https://github.com/0xDezzy/Unlimited-Outposts-CCR/releases/download/${{github.ref_name}}/Unlimited-Outposts-CCR_${GITHUB_REF:11}.zip" -O "release.zip"

    - name: Upload
      uses: hmlendea/nexusmods-update@latest
      with:
        account_email_address: ${{secrets.NEXUS_UPLOADER_USERNAME}}
        account_password: ${{secrets.NEXUS_UPLOADER_PASSWORD}}
        nexus_game_id: "starfield"
        nexus_mod_id: "2924"
        mod_file_name: "Unlimited Outposts - CCR"
        mod_version: ${{github.ref_name}}
        file_description: "Changelog: https://github.com/0xDezzy/Unlimited-Outposts-CCR/releases/${{github.ref_name}}"
        file_path: "release.zip"